### ISSUE TITLE
When entering the lobby, received 'private fields are not currently supported'

### ISSUE THREAD

**Issue by andy5995** [rossenburgg/godseye#8]
I got this message when entering the lobby but it didn't appear to cause a problem:

>ERROR: JavaScript error: godseye_data/defbot.py line 1
private fields are not currently supported
  onLogin@gui/prelobby/login/login.js:50:9
  onTick@gui/prelobby/common/feedback/feedback.js:27:34
  __eventhandler57 (Tick)@__internal(15) Tick:1:1

**Comment by rossenburgg** [comment]
TY @andy5995 , I noticed some files got excluded , like the Python files and music files ( probably the music file was excluded by @StanleySweet maybe for copyright reasons ). Also you can still use without  defbot.py for now. And there’s one more thing - when you press on the security button where you are supposed to be able to change your password - it will trigger an error saying xmpp client is not established…will work on getting them functional ty

**Comment by StanleySweet** [comment]
Music files were removed for size reasons. If they are replacement for existing music they should have different names and modify the music.js file :)
I didn't know you used the data folder though I thought it was a leftover.
As for copyright you need to make sure you have the rights to copy and distribute your tracks.

**Comment by rossenburgg** [comment]
Resolved
